// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(zalo)/chat-iframe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat-iframe">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/chat-iframe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(zalo)/directory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/directory">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/directory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(zalo)/group/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/group">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/group/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(zalo)/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(zalo)/invite/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/invite/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(zalo)/moments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/moments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/moments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(zalo)/moments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/moments">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/moments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(zalo)/profile/[user]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/[user]">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/profile/[user]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(zalo)/setting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setting">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/setting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mini/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mini">> = Specific
  const handler = {} as typeof import("../../src/app/mini/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mini/sso/callback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mini/sso/callback">> = Specific
  const handler = {} as typeof import("../../src/app/mini/sso/callback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/refresh">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/groups/invite/[code]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/groups/invite/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/api/groups/invite/[code]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/groups/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/groups/invite">> = Specific
  const handler = {} as typeof import("../../src/app/api/groups/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/groups/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/groups/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/groups/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/groups">> = Specific
  const handler = {} as typeof import("../../src/app/api/groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/livekit/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/livekit/token">> = Specific
  const handler = {} as typeof import("../../src/app/api/livekit/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sso/consume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sso/consume">> = Specific
  const handler = {} as typeof import("../../src/app/api/sso/consume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sso/issue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sso/issue">> = Specific
  const handler = {} as typeof import("../../src/app/api/sso/issue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload/progress">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(zalo)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(zalo)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
