var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/mini/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8a983ed5._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_672bc551._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1d3000f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a2112212._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__1808f05c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_mini_page_actions_df4330f1.js")
R.m(41315)
module.exports=R.m(41315).exports
