// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/chat-iframe" | "/directory" | "/group" | "/home" | "/invite/[code]" | "/login" | "/mini" | "/mini/sso/callback" | "/moments" | "/moments/[id]" | "/profile/[user]" | "/setting"
type AppRouteHandlerRoutes = "/api/auth/refresh" | "/api/groups" | "/api/groups/invite" | "/api/groups/invite/[code]" | "/api/groups/join" | "/api/livekit/token" | "/api/messages" | "/api/posts" | "/api/sso/consume" | "/api/sso/issue" | "/api/upload" | "/api/upload/progress" | "/api/users" | "/api/users/me"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/refresh": {}
  "/api/groups": {}
  "/api/groups/invite": {}
  "/api/groups/invite/[code]": { "code": string; }
  "/api/groups/join": {}
  "/api/livekit/token": {}
  "/api/messages": {}
  "/api/posts": {}
  "/api/sso/consume": {}
  "/api/sso/issue": {}
  "/api/upload": {}
  "/api/upload/progress": {}
  "/api/users": {}
  "/api/users/me": {}
  "/chat-iframe": {}
  "/directory": {}
  "/group": {}
  "/home": {}
  "/invite/[code]": { "code": string; }
  "/login": {}
  "/mini": {}
  "/mini/sso/callback": {}
  "/moments": {}
  "/moments/[id]": { "id": string; }
  "/profile/[user]": { "user": string; }
  "/setting": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
