var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(zalo)/setting/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__019b2716._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_1e1cb197._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1d3000f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a2112212._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__1808f05c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(zalo)_layout_tsx_70b047a2._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(zalo)_setting_page_actions_1ec89607.js")
R.m(51449)
module.exports=R.m(51449).exports
